2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Configure stats pid to 106805
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Loading settings from /home/joaquin_l_calvo/.config/wandb/settings
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Loading settings from /home/joaquin_l_calvo/Trento/Data_Mining/Data-Mining-Project/wandb/settings
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-10 17:32:38,389 WARNING MainThread:106805 [wandb_setup.py:_flush():79] Could not find program at -m src.scripts.run_train_als
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m src.scripts.run_train_als'}
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_init.py:_log_setup():533] Logging user logs to /home/joaquin_l_calvo/Trento/Data_Mining/Data-Mining-Project/wandb/offline-run-20241210_173238-xu88piox/logs/debug.log
2024-12-10 17:32:38,389 INFO    MainThread:106805 [wandb_init.py:_log_setup():534] Logging internal logs to /home/joaquin_l_calvo/Trento/Data_Mining/Data-Mining-Project/wandb/offline-run-20241210_173238-xu88piox/logs/debug-internal.log
2024-12-10 17:32:38,390 INFO    MainThread:106805 [wandb_init.py:init():619] calling init triggers
2024-12-10 17:32:38,390 INFO    MainThread:106805 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'rank': 10, 'max_iter': 20, 'reg_param': 0.1, 'implicit_prefs': True, 'alpha': 1.0, 'cold_start_strategy': 'drop', 'model_save_path': 'saved_models/als_model'}
2024-12-10 17:32:38,390 INFO    MainThread:106805 [wandb_init.py:init():664] wandb.init() called when a run is still active
2024-12-10 18:10:06,372 WARNING MsgRouterThr:106805 [router.py:message_loop():75] message_loop has been closed
